/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\public\model\model.glb 
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { useControls } from 'leva'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('./model/model.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions,names } = useAnimations(animations, group)
  const mode = props.mode

  useEffect(
    ()=>{
        actions[mode].reset().fadeIn(0.5).play();
        return () => {
            actions[mode].reset().fadeOut(0.5);
          };
    },[mode])
  return (
    <group ref={group} dispose={null}>
      <group name="Scene">
        <group name="T-pose">
          <primitive object={nodes.Hips} />
          <skinnedMesh name="Wolf3D_Body014" geometry={nodes.Wolf3D_Body014.geometry} material={materials['Wolf3D_Body.034']} skeleton={nodes.Wolf3D_Body014.skeleton} />
          <skinnedMesh name="Wolf3D_Hair014" geometry={nodes.Wolf3D_Hair014.geometry} material={materials['Wolf3D_Hair.034']} skeleton={nodes.Wolf3D_Hair014.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Bottom014" geometry={nodes.Wolf3D_Outfit_Bottom014.geometry} material={materials['Wolf3D_Outfit_Bottom.034']} skeleton={nodes.Wolf3D_Outfit_Bottom014.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Footwear014" geometry={nodes.Wolf3D_Outfit_Footwear014.geometry} material={materials['Wolf3D_Outfit_Footwear.034']} skeleton={nodes.Wolf3D_Outfit_Footwear014.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Top014" geometry={nodes.Wolf3D_Outfit_Top014.geometry} material={materials['Wolf3D_Outfit_Top.034']} skeleton={nodes.Wolf3D_Outfit_Top014.skeleton} />
          <skinnedMesh name="EyeLeft014" geometry={nodes.EyeLeft014.geometry} material={materials['Wolf3D_Eye.034']} skeleton={nodes.EyeLeft014.skeleton} morphTargetDictionary={nodes.EyeLeft014.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft014.morphTargetInfluences} />
          <skinnedMesh name="EyeRight014" geometry={nodes.EyeRight014.geometry} material={materials['Wolf3D_Eye.034']} skeleton={nodes.EyeRight014.skeleton} morphTargetDictionary={nodes.EyeRight014.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight014.morphTargetInfluences} />
          <skinnedMesh name="Wolf3D_Head014" geometry={nodes.Wolf3D_Head014.geometry} material={materials['Wolf3D_Skin.034']} skeleton={nodes.Wolf3D_Head014.skeleton} morphTargetDictionary={nodes.Wolf3D_Head014.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Head014.morphTargetInfluences} />
          <skinnedMesh name="Wolf3D_Teeth014" geometry={nodes.Wolf3D_Teeth014.geometry} material={materials['Wolf3D_Teeth.034']} skeleton={nodes.Wolf3D_Teeth014.skeleton} morphTargetDictionary={nodes.Wolf3D_Teeth014.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Teeth014.morphTargetInfluences} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./model/model.glb')
